export const OPERATIONS = [
  {
    id: 'set-membership',
    title: 'Set Membership (x ∈ A)',
    description: 'Membership indicates that an element x is contained within set A.',
    category: 'Foundations',
    example: 'For A = {1, 2, 3}, we say 2 ∈ A but 5 ∉ A.',
  },
  {
    id: 'cardinality',
    title: 'Cardinality (|A|)',
    description: 'The size of a set counts how many distinct elements it contains.',
    category: 'Foundations',
    example: 'If A = {1, 3, 5, 7}, then |A| = 4.',
  },
  {
    id: 'subset',
    title: 'Subset (A ⊆ B)',
    description: 'Every element of set A also belongs to set B, so A fits entirely inside B.',
    category: 'Relationships',
    example: 'If A = {0, 1} and B = {0, 1, 2}, then A ⊆ B.',
  },
  {
    id: 'set-equality',
    title: 'Set Equality (A = B)',
    description: 'Two sets are equal when they contain exactly the same elements.',
    category: 'Relationships',
    example: 'A = {1, 2, 3} equals B = {3, 2, 1}. Order does not matter!',
  },
  {
    id: 'union',
    title: 'Union (A ∪ B)',
    description: 'Elements that belong to set A or set B (or both).',
    category: 'Operations',
    example: 'If A = {1, 2} and B = {2, 3}, then A ∪ B = {1, 2, 3}.',
  },
  {
    id: 'intersection',
    title: 'Intersection (A ∩ B)',
    description: 'Elements shared by both sets A and B.',
    category: 'Operations',
    example: 'If A = {1, 2} and B = {2, 3}, then A ∩ B = {2}.',
  },
  {
    id: 'set-difference',
    title: 'Set Difference (A \\ B)',
    description: 'Elements that are in A while excluding any that belong to B.',
    category: 'Operations',
    example: 'If A = {1, 2, 3} and B = {2}, then A \\ B = {1, 3}.',
  },
  {
    id: 'complement',
    title: 'Complement (A̅)',
    description: 'Everything in the universal set except the elements of A.',
    category: 'Operations',
    example: 'In U = {1, 2, 3, 4}, if A = {1, 4} then A̅ = {2, 3}.',
  },
  {
    id: 'symmetric-difference',
    title: 'Symmetric Difference (A ⊕ B)',
    description: 'Elements that belong to exactly one of the sets.',
    category: 'Operations',
    example: 'A ⊕ B = {1, 3} when A = {1, 2} and B = {2, 3}.',
  },
  {
    id: 'disjoint-union',
    title: 'Disjoint Union (A ⨄ B)',
    description: 'Combines sets that share no elements, keeping their identities separate.',
    category: 'Advanced',
    example: 'If A = {a, b} and B = {1, 2}, a disjoint union labels elements so a ≠ 1 even if values match.',
  },
  {
    id: 'cartesian-product',
    title: 'Cartesian Product (A × B)',
    description: 'All ordered pairs (a, b) with a from A and b from B.',
    category: 'Advanced',
    example: 'If A = {x, y} and B = {1, 2}, then A × B = {(x,1), (x,2), (y,1), (y,2)}.',
  },
  {
    id: 'power-set',
    title: 'Power Set (𝒫(A))',
    description: 'The collection of every possible subset of A, including ∅ and A itself.',
    category: 'Advanced',
    example: 'For A = {1, 2}, 𝒫(A) = {∅, {1}, {2}, {1, 2}}.',
  },
  {
    id: 'k-subsets',
    title: 'k-Subsets',
    description: 'All subsets of A that have exactly k elements.',
    category: 'Advanced',
    example: 'The 2-subsets of {1, 2, 3} are {1,2}, {1,3}, {2,3}.',
  },
];

export default OPERATIONS;
